import solc from "solc";
import fs from "node:fs";

const source = fs.readFileSync("contracts/QuantToken.sol", "utf8");
const input = {
  language: "Solidity",
  sources: { "QuantToken.sol": { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};
const out = JSON.parse(solc.compile(JSON.stringify(input)));
const errs = (out.errors ?? []).filter((e) => e.severity === "error");
if (errs.length) { console.error(errs); process.exit(1); }
const c = out.contracts["QuantToken.sol"].QuantToken;
const ts = `/*
  Compiled QuantToken (launcher v1 template) — generated by scripts/compile-erc20.mjs.
  Source: contracts/QuantToken.sol · solc ${solc.version()}
  Clean fixed-supply ERC-20: no owner, no mint, no taxes.
*/
export const ERC20_TEMPLATE_ABI = ${JSON.stringify(c.abi)} as const;

export const ERC20_TEMPLATE_BYTECODE = "0x${c.evm.bytecode.object}" as const;
`;
fs.writeFileSync("lib/erc20-template.ts", ts);
console.log("bytecode bytes:", c.evm.bytecode.object.length / 2);
